### PR TITLE
Redirect root 2

### LINKED ISSUE #2: Adjust Root to Redirect to ‘/reminders’
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by JeffBuss**
Closes #2 

## Purpose

Index sucks. We want to land on the reminders page. Also we're going to make sure that an H1 is rendering.

## Approach

It redirects the user to reminders from index.

### Learning

We read the docs. We also read the top result on google on how to rename a branch since we forgot to add the issue number. We also just now realized we renamed it 1 instead of 2, so you'll notice a closed PR. Don't mind us.

[Redirecting routes in ember](https://guides.emberjs.com/v2.11.0/routing/redirection/#toc-toggle)

[How to rename a branch b/c we can't read instructions](https://www.google.com/search?q=change+branch+name+after+push&oq=change+branch+name+after+push&aqs=chrome..69i57.5094j0j1&sourceid=chrome&ie=UTF-8)

### Open Questions and Pre-Merge TODOs

Nothing to report

### Test coverage 

We adjusted the first test to check that we are redirecting users to /reminders from index. Also commented out the second assertion in test one and skipped test 2 (after importing skip of course!) since we are doing them out of order.

### Merge Dependencies and Related Work

Nothing to report

### Follow-up tasks

We're going to backtrack and complete issue [#1](https://github.com/turingschool-projects/1610-remember-7/issues/1)

### Screenshots

We'll take some next time team, our b.

#### After

### CODE REVIEW

File: app/router.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
+  this.route('reminders'), { path: '/reminders'};
```
Comment (martensonbj) [inline app/router.js]: If your route is `reminders` you don't need the path to also specify reminders - it will do this by default. This means you can remove the `{ path: '/reminders'}` bit.

File: app/templates/index.hbs [hunk 2]
```diff
@@ -0,0 +1,3 @@
+<h1>Index</h1>
```
Comment (martensonbj) [inline app/templates/index.hbs]: We won't need this template. You can delete it.

File: tests/unit/routes/index-test.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/unit/routes/index-test.js]: Routes end up being tested using acceptance tests - you can delete this file.

File: tests/unit/routes/reminders-test.js [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/unit/routes/reminders-test.js]: See above comment about testing routes.

File: app/routes/reminders.js [hunk 5]
```diff
@@ -0,0 +1,5 @@
+import Ember from 'ember';
```
Comment (martensonbj) [inline app/routes/reminders.js:1]: I'm leaving this here because I know you're about to go back and add functionality to display reminders, but in the future any file not being used should not be included in your PR.

**Review by martensonbj — CHANGES_REQUESTED** [review]
Few clean up things.

**Comment by JeffBuss** [comment]
@martensonbj Changes completed

**Review by martensonbj — APPROVED** [review]
✈️
